osx_image: xcode9.3
language: objective-c
xcode_project: liferay-analytics.xcodeproj
xcode_sdk: iphonesimulator
xcode_scheme: liferay-analytics

env:
  global:
    - SCHEME="liferay-analytics"
    - OS="11.2"

before_install:
  - gem install slather
  - brew install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar https://oss.sonatype.org/service/local/repositories/releases/content/com/codacy/codacy-coverage-reporter/4.0.1/codacy-coverage-reporter-4.0.1-assembly.jar

after_success:
  - java -jar ~/codacy-coverage-reporter-assembly-latest.jar report -l Swift -r ${TRAVIS_BUILD_DIR}/reports/cobertura.xml 

script:
  - xcodebuild clean test -project liferay-analytics.xcodeproj -scheme liferay-analytics -destination "platform=iOS Simulator,name=iPhone 8" -enableCodeCoverage YES clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - slather coverage  